# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]
    
env:
  ENV_KEY: env_value 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-output:
   name: test output
   runs-on: ubuntu-latest
   steps:
   
     - name: Checkout
       uses: actions/checkout@v2
     - id: step1
       name: step ONE
       run: |
         echo "::set-output name=outKey::outValue" 
         echo ${{ env.ENV_KEY }}
         echo ${{ github.ref }}
         if [[ ${{ github.ref }} == "refs/heads/master" ]]; then
           echo "master branch"
         elif [[ ${{ github.ref }} == "refs/heads/dev" ]]; then
           echo "dev branch"
         fi  
         
     - id: get-env
       run: echo "::set-output name=environment::prd"
         
     - id: step2
       name: step TWO
       run: echo ${{ steps.step1.outputs.outKey }}
     
     - id: step3
       name: conditional step 3
       if: steps.get-env.outputs.environment == 'prd'
       run: echo "prd step 3 condition matches"
        
     - id: step4
       name: conditional step 4
       if: steps.get-env.outputs.environment == 'dev'
       run: echo "dev step 4 condition matches"
       
     - id: step5
       name: step five
       run: |
         echo ${github.event}
         ${{ github.event.pull_request.base.ref }}
         ${{ github.event.pull_request.base.sha }}
         ${{ github.event.base_ref }}
         ${{ github.event.before }}
#   test:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         os: [ubuntu-latest]
#         SCALA_VER: ["2.11", "2.12"]
#         SPARK_VER: ["3.0", "2.4", "2.3"]
#         exclude:
#           - SCALA_VER: 2.12
#             SPARK_VER: 2.3
#           - SCALA_VER: 2.11
#             SPARK_VER: 3.0
            
#     steps:
#       - name: test
#         env:
#           SHA: ${{github.sha}}
#         run: |
#           echo 'the version ${{ matrix.SPARK_VER }}'
#           echo 'scala version ${{matrix.SCALA_VER}}'
#           echo ${{ matrix.SCALA_VER == '2.12' }}
#           echo ${{ github.ref }}
#           echo $SHA
#           gpg -h
#       - name: condition
#         if: ${{ matrix.SCALA_VER == '2.12' }}
#         run: echo 'scala 2.12'
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!
    
#     - name: docker
#       run: |
#         docker --version
#         docker run hello-world

#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
#         echo hahaah > test
#         cat test
#     - name: SNAP version deployment
#       if: ${{ startsWith( github.ref, 'refs/tags/test-' ) && contains( github.ref, '-RC' ) }}
#       run: |
#         RC_VER=$(echo ${{ github.ref }} | cut -d'-' -f 3)
#         echo "mvn clean deploy scala:doc -ntp -B -DskipTests -Dchangelist=-$RC_VER"
